name: Update Profile Data

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: readme-activity-graph/activity-readme@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
